context:
  version: 1.0

package:
  name: lzfse
  version: ${{ version }}

source:
  url: https://github.com/lzfse/lzfse/archive/lzfse-${{ version }}.zip
  sha256: 941c2e39493f7669ee4547f3b3d9007ffb0d33c6e3d5990af5423b7b77b90bad

build:
  number: 1

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - python *
    - cmake
    - make

tests:
  - script:
    - lzfse -h
    - if: unix
      then:
        - test -f ${PREFIX}/include/lzfse.h
        - test -f ${PREFIX}/lib/liblzfse${SHLIB_EXT}
    - if: win
      then:
        - if not exist %LIBRARY_PREFIX%\bin\lzfse.dll exit 1
        - if not exist %LIBRARY_PREFIX%\lib\lzfse.lib exit 1
        - if not exist %LIBRARY_PREFIX%\include\lzfse.h exit 1

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Reference C implementation of the LZFSE compressor
  description: |
    LZFSE is a Lempel-Ziv style data compression algorithm using Finite State
    Entropy coding. It targets similar compression rates at higher compression
    and decompression speed compared to deflate using zlib.
  homepage: https://github.com/lzfse/lzfse

extra:
  recipe-maintainers:
    - danielnachun
    - rmax
