appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Mxs7RaOA2duBKJWjgQ6DfbkYxuG93Wn2NN3TKJIlfUgSQy7L5AHRX2Fur4vMODzJoggc+qZwBfqgbY2jEUs49bgVh7qBuI5VFkp+4vQvG8uOvEFUKA3Utu2kP77045DVJjY4bbD2O3IVKy/+YIHYgsmlTWSVLr6lhBbU2AkZm1F6DFTodzG/jbZjEIFoNobi26f/0Bb/mVBrflVmKTblBHj2ViM6+Vo6QnGou/PHTDLznu4sNG4YL2T4QV711KHM0lSWMThdsQosiDxmZ9/WwlwdVd5qps+eQCjcKd86/cQM49ricpHb/Q8XXdCkqQrHpVuaGwpdRHuxc83UYHRFTgNylM5z0CUIZcM67iKDi0NNZLt5rPxy7QLi4lvU13c9FjctmEvLMuvU1hduAzI+FZpxN65Hs/sUj4O783g0+s7ix+Twh/jPXC9r6ZX6wUcaVbszNsVvKXvhFNPDFuq+oc+0I0xD4qygqwUlYt57lY4/1ShVWRP0KtIxPpZ2J3U6gxU68wRVjuP0mkYWm6+/msJJA4xa/n9kdAFm7lDCx08L7nviWMS8XWf8iPDYxcpsdsjdiB4q364kjn2HuzqURIzlql8Pkd7Jm293d0wiH6rukds4y0Ha8CbZeeWwyhBDsYofgVY4+Y9onJXnnBvmc9HOE/ZJrqRTYGbI3b7Bwxs=}
